services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: horse-racing-api-container
    ports:
      - "9000:9000"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Ánh xạ thư mục lưu ảnh từ container ra ngoài VPS để không bị mất khi deploy lại
      - ./uploads:/app/uploads
    logging:
      driver: "json-file"
      options:
        max-size: "10mb"
        max-file: "3"